### ISSUE TITLE
Dragoon Rotation bug

### ISSUE THREAD

**Issue by ElrenaSyl** [FFXIV-CombatReborn/RebornRotations#103]
Combo consistantly break after "Spiral Blow" & "Lance barrage" and go back to the beginning in a loop never completing either of the combo proper, i didnt tweak anything related to the rotation so i'm at loss why it's not working. OGCD seem to work fine even if it's hard to tell without the full combo rotation.

**Comment by LTS-FFXIV** [comment]
Fixed
