### ISSUE TITLE
SMN carbuncle not getting summoned

### ISSUE THREAD

**Issue by omfgdahoe** [FFXIV-CombatReborn/RebornRotations#113]
I'm running doma castle lvl 68 and rsr doesn't try to summon carbuncle before or in fight. Instead of summoning rsr tries spamming summon ifrit or keeps spamming ruin III in diffrent situations.

**Comment by LTS-FFXIV** [comment]
Fixed in recent update [7.0.1.42](https://github.com/FFXIV-CombatReborn/RebornRotations/releases/tag/7.0.1.42)
