### ISSUE TITLE
Failed to invoke next action error

### ISSUE THREAD

**Issue by Meiby23** [FFXIV-CombatReborn/RebornRotations#115]
It was working today, but I tried to run some auto dungeon and it is failing to respond in general because it need me to update. "Invalid rotation" " Please update to the latest version".

**Comment by LTS-FFXIV** [comment]
Please provide a screenshot of where you are getting that error

**Comment by Meiby23** [comment]
![image_2024-07-20_024809187](https://github.com/user-attachments/assets/ff88d4c9-949a-4d2c-8e8e-6ca264b6fb04)

**Comment by LTS-FFXIV** [comment]
Is this happening on any other class?

**Comment by Meiby23** [comment]
All of them currently.
I swapped to Dancer, Reaper and Warrior. 
It was working for Rdm while I was using autoduty this morning. But not anymore.

**Comment by LTS-FFXIV** [comment]
where does it say "invalid" and "update to the newest version"

**Comment by Meiby23** [comment]
![Uploading image_2024-07-20_025315944.png…]()

**Comment by Meiby23** [comment]
One sec, can't open it

**Comment by Meiby23** [comment]
![234](https://github.com/user-attachments/assets/833a60b1-6fa1-488f-ab4b-1e245d9ee809)

**Comment by LTS-FFXIV** [comment]
This is a generalized error message, hence the "or contact the combat reborn team" part

if you are fully updated then that is not the issue, by the looks of it there was an error invoking an action

**Comment by Meiby23** [comment]
Yes that sounds more accurate. I'm going to restart and try it again.

**Comment by Meiby23** [comment]
Yeah after restarting the game. It still has a issue with invoking the next action.
