### ISSUE TITLE
ARC/BRD Does not use abilities granted by Hawk's Eye buff

### ISSUE THREAD

**Issue by Arrakki** [FFXIV-CombatReborn/RebornRotations#143]
ARC/BRD Does not use abilities granted by Hawk's Eye buff such as Straight Shot, Refulgent Arrow, Wide Volley or Shadowbite.

**Comment by YsEmei** [comment]
This is a big deal. Bard is almost in auto shot mode as it currently is. StraightShotReady was replaced with Hawk's Eye

**Comment by Arrakki** [comment]
Looks like Barrage ability is not properly recognized as even after unlocking the ability, it is not being used and System Warnings keeps repeating that the ability needs to be unlocked.

**Comment by LTS-FFXIV** [comment]
fixed
