### ISSUE TITLE
ARC/BRD Does not recognize Barrage Ability. Wide Volley ability not used

### ISSUE THREAD

**Issue by Arrakki** [FFXIV-CombatReborn/RebornRotations#151]
Rotation generates System Warnings about Barrage not being unlocked when it is unlocked and usable:
![image](https://github.com/user-attachments/assets/7a9b919a-d2b7-40e7-9211-906256c4a87f)

Ability Quick Nock (potency 110) is prioritized over Wide Volley (potency 140/220). Wide Volley does not seem to be used at all.

**Comment by LTS-FFXIV** [comment]
Fixed on next release
