### ISSUE TITLE
BRD not using Blast Arrow

### ISSUE THREAD

**Issue by YsEmei** [FFXIV-CombatReborn/RebornRotations#206]
Checked multiple logs. It's never casting a single **Blast Arrow**.
```
Apex Arrow
Additional Effect: Grants Blast Arrow Ready upon execution while Soul Voice Gauge is 80 or higher
```
So it should cast **Apex Arrow** again when it turns into **Blast Arrow**

**Comment by LTS-FFXIV** [comment]
Reset your plugin
