### ISSUE TITLE
Bard rotation PvE

### ISSUE THREAD

**Issue by omfgdahoe** [FFXIV-CombatReborn/RebornRotations#41]
Tried bard at lvl 50 or 60 alliance raid and he doesn't use Straight Shot at all in single rotation and keeps spamming Heavy Shot, in AoE Quick Nock is getting spammed. If you get Hawk's Eye trigger he doesn't use it at all, honestly I'm not even sure if the Hawk's Eye is something new because i barely played bard before dt

**Comment by Tykku** [comment]
Merging with #48
