### ISSUE TITLE
Feature request: Add manafication usage outside of embolden window.

### ISSUE THREAD

**Issue by AnonLoid** [FFXIV-CombatReborn/RebornRotations#69]
Hi! 
Im asking to add additional config for RDM rotation to use manafication regardless if i have embolden or no. 
Let me explain. Embolden window is 20 seconds, sometimes RSR cant keep up with it (example: if i have 100/100 mana, manafication only get used on LAST melee combo out of 3), OR if i resolve some boss mechanic and embolden buff runs off. 
That would be nice to have option for dummy rsr users like me, for rsr using manafication outside of embolden, just not to press additional button.
You know, because we are lazy.

![image](https://github.com/FFXIV-CombatReborn/RebornRotations/assets/43205986/e317eb99-dec3-4c25-bac3-18c5662e4414)

**Comment by Tykku** [comment]
This will be fixed by tying the 2 together. If you want this outside of it just missing it please reopen the issue

**Comment by AnonLoid** [comment]
Good enough, i just want to not lose manafication charges
