### ISSUE TITLE
Reaper Dawntrail Rotation issues

### ISSUE THREAD

**Issue by Clapper12** [FFXIV-CombatReborn/RebornRotations#7]
1 - Rotation does not include PERFECTIO when all conditions are met (Plentiful Harvest+Communio used)
2 - Rotation does not Prioritize EXECUTIONERS (Gallows/GIBBET - Guillotine) when Gluttony is used Which is respectively 200 potency HIGHER then base (500).

**Comment by Clapper12** [comment]
Also noticed it does not seem to prioritize applying Deaths Design

**Comment by Clapper12** [comment]
Looks like its doing soul slice and discarding the gibbet/gallows executioner following Gluttony

![image](https://github.com/FFXIV-CombatReborn/RebornRotations/assets/174365724/8300b60d-0734-4867-a459-65fb301314fc)

**Comment by Tykku** [comment]
Fixed in #21
