### ISSUE TITLE
MCH: No Full Metal Field Use On AOE

### ISSUE THREAD

**Issue by GREYsaurus** [FFXIV-CombatReborn/RebornRotations#8]
Like the title says no FMF use on AOE rotation. Could be similar to the problem that was no excavator on ST.

Keep up the good work and buy a beer or a drink with those Kofi's I got you. You deserve it.

-Mirai

**Comment by Tykku** [comment]
I ordered a pizza, is this still happening?

**Comment by GREYsaurus** [comment]
Just ran an expert. Still happening.

**Comment by Tykku** [comment]
Fixed
