### ISSUE TITLE
NIN Tries to use Kunais Bane (and presumably Trick Attack) when it is not on cooldown but not enabled (ie when not Hidden/Shadow Walking)

### ISSUE THREAD

**Issue by nihilistzsche** [FFXIV-CombatReborn/RebornRotations#87]
Basically,
  Whenever you are in GCD and have no better option it will try to use Kunai's Bane, I presume Trick Attack though I have not done any synced content since I noticed this.  It will spam try to use Kunai's Bane and in fact will even try to use it while doing Ninjutsu and cause Bunny.

**Comment by Tykku** [comment]
Merging with #30
